name: CI/CD

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Version
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        HASH=$(git rev-parse --short HEAD)
        echo "export default \"#$HASH\";" > src/app/version.ts
    - name: Build
      run: npm run build
    - name: Deploy
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}